Models/DbCntext.cs
namespace Asp.netMVCCRUD.Models
{
    public class DbCntext
    {
    }
}

Models/ErrorViewModel.cs
using System;

namespace Asp.netMVCCRUD.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Models/Imone.cs
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Threading.Tasks;

namespace Asp.netMVCCRUD.Models
{
    public class Imone
    {
        [Key]
        public int Id { get; set; }
        
        [Column(TypeName ="nvarchar(250)")]
        [Required(ErrorMessage = "Šis laukas negali būti tuščias")]
        
        public string Pavadinimas { get; set; }
        [Column(TypeName = "varchar(150)")]
        [DisplayName("El. Paštas")]
        public string ElPastas { get; set; }
        [Column(TypeName = "varchar(150)")]
        [DisplayName("Blogas El. Paštas")]
        public string BlogasElPastas { get; set; }
        [Column(TypeName = "varchar(100)")]
        [DisplayName("Kontaktinis Tel.Nr")]
        public string TelNr { get; set; }
        [Column(TypeName = "varchar(50)")]
        public string Apskritis { get; set; }
        [Column(TypeName = "varchar(50)")]
        public string VMVT { get; set; }
        [Column(TypeName = "varchar(250)")]
        [DisplayName("Kita Info")]
        public string KitaInfo { get; set; }
        [Column(TypeName = "varchar(250)")]
        [DisplayName("Aktuali Veikla")]
        public string AktualiVeikla { get; set; }
        [Column(TypeName = "varchar(25)")]
        [DisplayName("Įmonės Kodas")]
        public string ImonesKodas { get; set; }

    }
}

Models/ImoneContext.cs
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Asp.netMVCCRUD.Models
{
    public class ImoneContext:DbContext
    {
        public ImoneContext(DbContextOptions<ImoneContext> options): base(options)
        {

        }
        public DbSet<Imone> Imones { get; set; }
    }
}

Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using Asp.netMVCCRUD.Models;

namespace Asp.netMVCCRUD.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Controllers/ImonesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Asp.netMVCCRUD.Models;

namespace Asp.netMVCCRUD.Controllers
{
    public class ImonesController : Controller
    {
        private readonly ImoneContext _context;

        public ImonesController(ImoneContext context)
        {
            _context = context;
        }

        // GET: Imones
        public async Task<IActionResult> Index()
        {
            return View(await _context.Imones.ToListAsync());
        }

     
        

        // GET: Imones/Create
        public IActionResult AddOrEdit(int id = 0)
        {
            if(id==0)
                return View(new Imone());
            else
                return View(_context.Imones.Find(id));
        }

        // POST: Imones/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> AddOrEdit([Bind("Id,Pavadinimas,ElPastas,BlogasElPastas,TelNr,Apskritis,VMVT,KitaInfo,AktualiVeikla,ImonesKodas")] Imone imone)
        {
            if (ModelState.IsValid)
            {
                if(imone.Id == 0)
                    _context.Add(imone);
                else
                    _context.Update(imone);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(imone);
        }

        // GET: Imones/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var imone = await _context.Imones.FindAsync(id);
            if (imone == null)
            {
                return NotFound();
            }
            return View(imone);
        }

        // POST: Imones/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Pavadinimas,ElPastas,BlogasElPastas,TelNr,Apskritis,VMVT,KitaInfo,AktualiVeikla,ImonesKodas")] Imone imone)
        {
            if (id != imone.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(imone);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ImoneExists(imone.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(imone);
        }

        // GET: Imones/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {

            var imone = await _context.Imones.FindAsync(id);
            _context.Imones.Remove(imone);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));

        }

        // POST: Imones/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var imone = await _context.Imones.FindAsync(id);
            _context.Imones.Remove(imone);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool ImoneExists(int id)
        {
            return _context.Imones.Any(e => e.Id == id);
        }
    }
}

Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Įmonių Duomenų Bazė</h1>
    <a asp-controller="Imones"asp-action="Index">Įmonių sąrašas</a>.</p>
</div>

Views/Imones/AddOrEdit.cshtml
@model Asp.netMVCCRUD.Models.Imone

@{
    ViewData["Title"] = "Create";
}

<h4>Įmonės Forma</h4>
<hr />
<div class="row">
    <div class="col-md-6">
        <form asp-action="AddOrEdit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="ImonesKodas" class="control-label"></label>
                <input asp-for="ImonesKodas" class="form-control" />
                <span asp-validation-for="ImonesKodas" class="text-danger"></span>
            </div>
            
            <div class="form-group">
                <label asp-for="Pavadinimas" class="control-label"></label>
                <input asp-for="Pavadinimas" class="form-control" />
                <span asp-validation-for="Pavadinimas" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ElPastas" class="control-label"></label>
                <input asp-for="ElPastas" class="form-control" />
                <span asp-validation-for="ElPastas" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="BlogasElPastas" class="control-label"></label>
                <input asp-for="BlogasElPastas" class="form-control" />
                <span asp-validation-for="BlogasElPastas" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="TelNr" class="control-label"></label>
                <input asp-for="TelNr" class="form-control" />
                <span asp-validation-for="TelNr" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Apskritis" class="control-label"></label>
                <input asp-for="Apskritis" class="form-control" />
                <span asp-validation-for="Apskritis" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="VMVT" class="control-label"></label>
                <input asp-for="VMVT" class="form-control" />
                <span asp-validation-for="VMVT" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="KitaInfo" class="control-label"></label>
                <input asp-for="KitaInfo" class="form-control" />
                <span asp-validation-for="KitaInfo" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="AktualiVeikla" class="control-label"></label>
                <input asp-for="AktualiVeikla" class="form-control" />
                <span asp-validation-for="AktualiVeikla" class="text-danger"></span>
            </div>
            <div class="form-row">
                <div class="form-group col-md-6">
                    <input type="submit" value="Patvirtinti" class="btn btn-primary btn-block" />
                </div>
                <div class="form-group col-md-6">
                    <a asp-action="Index" class="btn btn-secondary btn-block"><i class="fa fa-table"></i>Atgal į sąrašą</a>
                </div>
            </div>
        </form>
    </div>
</div>



@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/Imones/Index.cshtml
@model IEnumerable<Asp.netMVCCRUD.Models.Imone>

@{
    ViewData["Title"] = "Index";
}

<h4>Įmonės</h4>

<hr />


<table class="table table-hover">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Pavadinimas)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.ElPastas)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.BlogasElPastas)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.TelNr)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Apskritis)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.VMVT)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.KitaInfo)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.AktualiVeikla)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.ImonesKodas)
            </th>
            <th
                ><a asp-action="AddOrEdit"class="btn btn-outline-success"><i class="far fa-plus-square"></i>Įmonė</a>
            </th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Pavadinimas)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.ElPastas)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.BlogasElPastas)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.TelNr)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Apskritis)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.VMVT)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.KitaInfo)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.AktualiVeikla)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.ImonesKodas)
            </td>
            <td>
                <a asp-action="AddOrEdit" asp-route-id="@item.Id"><i class="fa fa-marker fa-lg"></i></a>
                <a asp-action="Delete" asp-route-id="@item.Id" class="text-danger ml-1" onclick="return confirm('Ar tikrai norite pašalinti šią įmonę iš sąrašo?')"><i class="fa fa-trash-alt fa-lg"></i></a>
            </td>
        </tr>
}
    </tbody>
</table>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Įmonių sąrašas</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <script src="https://kit.fontawesome.com/cb3bc33fba.js"crossorigin="anonymous"></script>
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Įmonių duomenų bazė</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Imones" asp-action="Index">Sąrašas</a>
                        </li>
                        
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2020 - Asp.netMVCCRUD - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>